[package]
name = "aoc2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "day-01"

[[bin]]
name = "day-02"

[dependencies]
regex = "1.10.2"
